

## An int array
xint = [ 1, 2, 3 ]

## A double array
yflt = [ 1.1, 2.2, 3.3 ]

## A char array
ztxt = [ "the", "quick", "brown", "fox" ]

## No logical array

## A nested array
aa = [ [ 1, 2], [ 3, 4] ]

## A twice nested array
bb = [ [ 1, 2], [ [3, 4], [5, 6 ] ] ]
